/**
 * Bake the public `dsh-plugin` topic into the node half as an offline fallback.
 *
 * Run `pnpm catalog` before a release. An authenticated `gh` session raises
 * the search rate limit, but all indexed repositories are public.
 */

import { execFileSync } from 'node:child_process'
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const topic = 'dsh-plugin'
const query = `topic:${topic} is:public archived:false`
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'src', 'catalog-snapshot.ts')

const raw = execFileSync(
  'gh',
  [
    'api', '--paginate', '--slurp', '--method', 'GET', 'search/repositories',
    '-f', `q=${query}`, '-f', 'sort=updated', '-f', 'order=desc', '-f', 'per_page=100',
  ],
  { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
)

const pages = JSON.parse(raw)
const seen = new Set()
const plugins = pages
  .flatMap((page) => Array.isArray(page?.items) ? page.items : [])
  .filter((repo) => repo?.archived !== true && repo?.disabled !== true && repo?.fork !== true)
  .filter((repo) => Array.isArray(repo?.topics) && repo.topics.includes(topic))
  .filter((repo) => typeof repo?.full_name === 'string' && typeof repo?.name === 'string' && typeof repo?.html_url === 'string')
  .filter((repo) => {
    const key = repo.full_name.toLowerCase()
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
  .map((repo) => ({
    slug: repo.full_name,
    name: repo.name,
    description: typeof repo.description === 'string' ? repo.description : '',
    url: repo.html_url,
    pushedAt: typeof repo.pushed_at === 'string' ? repo.pushed_at : '',
    tags: repo.topics.filter((value) => typeof value === 'string' && value !== topic),
  }))
  .sort((a, b) => b.pushedAt.localeCompare(a.pushedAt))

const header = `/**
 * GitHub-topic snapshot, generated by \`scripts/build-catalog.mjs\`.
 *
 * The offline floor for the dynamic ad tier: what {@link loadRegistry} serves
 * when live GitHub discovery is unavailable. Do not edit by hand — run
 * \`pnpm catalog\` instead.
 *
 * @module
 */

import type { SponsoredPlugin } from './protocol.ts'

/** Public \`dsh-plugin\` repositories as of the last snapshot refresh. */
export const CATALOG_SNAPSHOT: readonly SponsoredPlugin[] = `

await writeFile(out, `${header}${JSON.stringify(plugins, null, 2)}\n`, 'utf8')
console.log(`catalog-snapshot.ts: ${plugins.length} plugins, newest ${plugins[0]?.pushedAt ?? 'n/a'}`)
