/**
 * Bake a plugin-hub snapshot into the node half.
 *
 * The hub is private, so a user without a working `gh` login has no way to
 * read it at runtime. This snapshot is what they get instead: stale, but it
 * means the dynamic tier still has a rotation to show. Regenerate it whenever
 * the plugin is released — `pnpm run catalog` — and commit the result.
 *
 * Requires an authenticated `gh` with read access to the hub.
 */

import { execFileSync } from 'node:child_process'
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HUB_REPO = 'dsh-external/hub'
const OWNER = HUB_REPO.split('/')[0]
const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const out = join(root, 'src', 'catalog-snapshot.ts')

const raw = execFileSync(
  'gh',
  ['api', `repos/${HUB_REPO}/contents/catalog.json`, '-H', 'Accept: application/vnd.github.raw'],
  { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
)

const repos = JSON.parse(raw).repos ?? []
const plugins = repos
  .filter((repo) => repo?.hide !== true && repo?.empty !== true && typeof repo?.name === 'string' && typeof repo?.url === 'string')
  .map((repo) => ({
    slug: `${OWNER}/${repo.name}`,
    name: repo.name,
    description: typeof repo.note === 'string' && repo.note !== '' ? repo.note : (repo.description ?? ''),
    url: repo.url,
    pushedAt: repo.pushedAt ?? '',
    tags: Array.isArray(repo.tags) ? repo.tags.filter((tag) => typeof tag === 'string') : [],
  }))
  .sort((a, b) => b.pushedAt.localeCompare(a.pushedAt))

const header = `/**
 * Plugin-hub snapshot, generated by \`scripts/build-catalog.mjs\`.
 *
 * The offline floor for the dynamic ad tier: what {@link loadRegistry} serves
 * when neither \`gh\` nor a token can reach the private hub. Do not edit by
 * hand — run \`pnpm run catalog\` instead.
 *
 * @module
 */

import type { SponsoredPlugin } from './protocol.ts'

/** Hub contents as of the last release, newest push first. */
export const CATALOG_SNAPSHOT: readonly SponsoredPlugin[] = `

await writeFile(out, `${header}${JSON.stringify(plugins, null, 2)}\n`, 'utf8')
console.log(`catalog-snapshot.ts: ${plugins.length} plugins, newest ${plugins[0]?.pushedAt ?? 'n/a'}`)
